export interface Champion {
    id: number;
    name: string;
    category: string[];
    imageUrl: string;
}

const images = "/images/champions";
export const champions: Champion[] = [
    { id: 1, name: "AATROX", category: ["FIGHTER"], imageUrl: images + "AATROX.png" },
    { id: 2, name: "AHRI", category: ["MAGE", "ASSASSIN"], imageUrl: images + "AHRI.png" },
    { id: 3, name: "AKALI", category: ["ASSASSIN"], imageUrl: images + "AKALI.png" },
    { id: 4, name: "AKSHAN", category: ["MARKSMAN", "ASSASSIN"], imageUrl: images + "AKSHAN.png" },
    { id: 5, name: "ALISTAR", category: ["TANK", "SUPPORT"], imageUrl: images + "ALISTAR.png" },
    { id: 6, name: "AMUMU", category: ["TANK", "MAGE"], imageUrl: images + "AMUMU.png" },
    { id: 7, name: "ANIVIA", category: ["MAGE", "SUPPORT"], imageUrl: images + "ANIVIA.png" },
    { id: 8, name: "ANNIE", category: ["MAGE"], imageUrl: images + "ANNIE.png" },
    { id: 9, name: "APHELIOS", category: ["MARKSMAN"], imageUrl: images + "APHELIOS.png" },
    { id: 10, name: "ASHE", category: ["MARKSMAN", "SUPPORT"], imageUrl: images + "ASHE.png" },
    { id: 11, name: "AURELION SOL", category: ["MAGE"], imageUrl: images + "AURELION_SOL.png" },
    { id: 12, name: "AZIR", category: ["MAGE", "MARKSMAN"], imageUrl: images + "AZIR.png" },
    { id: 13, name: "BARD", category: ["SUPPORT", "MAGE"], imageUrl: images + "BARD.png" },
    { id: 14, name: "BEL´VETH", category: ["SUPPORT", "MAGE"], imageUrl: images + "BELVETH.png" },
    { id: 15, name: "BLITZCRANK", category: ["TANK", "SUPPORT"], imageUrl: images + "BLITZCRANK.png" },
    { id: 16, name: "BRAUM", category: ["SUPPORT", "TANK"], imageUrl: images + "BRAUM.png" },
    { id: 17, name: "BRIAR", category: ["FIGHTER", "ASSASSIN"], imageUrl: images + "BRIAR.png" },
    { id: 18, name: "CAITLYN", category: ["MARKSMAN"], imageUrl: images + "CAITLYN.png" },
    { id: 19, name: "CAMILLE", category: ["FIGHTER"], imageUrl: images + "CAMILLE.png" },
    { id: 20, name: "CASSIOPEIA", category: ["MAGE"], imageUrl: images + "CASSIOPEIA.png" },
    { id: 21, name: "CHO'GATH", category: ["TANK", "MAGE"], imageUrl: images + "CHOGATH.png" },
    { id: 22, name: "CORKI", category: ["MARKSMAN"], imageUrl: images + "CORKI.png" },
    { id: 23, name: "DARIUS", category: ["FIGHTER", "TANK"], imageUrl: images + "DARIUS.png" },
    { id: 24, name: "DIANA", category: ["FIGHTER", "MAGE"], imageUrl: images + "DIANA.png" },
    { id: 25, name: "DR. MUNDO", category: ["FIGHTER", "TANK"], imageUrl: images + "DR_MUNDO.png" },
    { id: 26, name: "DRAVEN", category: ["MARKSMAN"], imageUrl: images + "DRAVEN.png" },
    { id: 27, name: "EKKO", category: ["ASSASSIN", "FIGHTER"], imageUrl: images + "EKKO.png" },
    { id: 28, name: "ELISE", category: ["MAGE", "FIGHTER"], imageUrl: images + "ELISE.png" },
    { id: 29, name: "EVELYNN", category: ["ASSASSIN", "MAGE"], imageUrl: images + "EVELYNN.png" },
    { id: 30, name: "EZREAL", category: ["MARKSMAN", "MAGE"], imageUrl: images + "EZREAL.png" },
    { id: 31, name: "FIDDLESTICKS", category: ["MAGE", "SUPPORT"], imageUrl: images + "FIDDLESTICKS.png" },
    { id: 32, name: "FIORA", category: ["FIGHTER", "ASSASSIN"], imageUrl: images + "FIORA.png" },
    { id: 33, name: "FIZZ", category: ["ASSASSIN", "FIGHTER"], imageUrl: images + "FIZZ.png" },
    { id: 34, name: "GALIO", category: ["TANK", "MAGE"], imageUrl: images + "GALIO.png" },
    { id: 35, name: "GANGPLANK", category: ["FIGHTER"], imageUrl: images + "GANGPLANK.png" },
    { id: 36, name: "GAREN", category: ["FIGHTER", "TANK"], imageUrl: images + "GAREN.png" },
    { id: 37, name: "GNAR", category: ["FIGHTER", "TANK"], imageUrl: images + "GNAR.png" },
    { id: 38, name: "GRAGAS", category: ["FIGHTER", "MAGE"], imageUrl: images + "GRAGAS.png" },
    { id: 39, name: "GRAVES", category: ["MARKSMAN"], imageUrl: images + "GRAVES.png" },
    { id: 40, name: "GWEN", category: ["FIGHTER"], imageUrl: images + "GWEN.png" },
    { id: 41, name: "HECARIM", category: ["FIGHTER", "TANK"], imageUrl: images + "HECARIM.png" },
    { id: 42, name: "HEIMERDINGER", category: ["MAGE", "SUPPORT"], imageUrl: images + "HEIMERDINGER.png" },
    { id: 43, name: "HWEI", category: ["FIGHTER", "TANK"], imageUrl: images + "HWEI.png" },
    { id: 44, name: "ILLAOI", category: ["FIGHTER", "TANK"], imageUrl: images + "ILLAOI.png" },
    { id: 45, name: "IRELIA", category: ["FIGHTER", "ASSASSIN"], imageUrl: images + "IRELIA.png" },
    { id: 46, name: "IVERN", category: ["SUPPORT", "MAGE"], imageUrl: images + "IVERN.png" },
    { id: 47, name: "JANNA", category: ["SUPPORT", "MAGE"], imageUrl: images + "JANNA.png" },
    { id: 48, name: "JARVAN IV", category: ["TANK", "FIGHTER"], imageUrl: images + "JARVAN_IV.png" },
    { id: 49, name: "JAX", category: ["FIGHTER", "ASSASSIN"], imageUrl: images + "JAX.png" },
    { id: 50, name: "JAYCE", category: ["FIGHTER", "MARKSMAN"], imageUrl: images + "JAYCE.png" },
    { id: 51, name: "JHIN", category: ["MARKSMAN", "MAGE"], imageUrl: images + "JHIN.png" },
    { id: 52, name: "JINX", category: ["MARKSMAN"], imageUrl: images + "JINX.png" },
    { id: 53, name: "K´SANTE", category: ["MARKSMAN", "ASSASSIN"], imageUrl: images + "KSANTE.png" },
    { id: 54, name: "KAI'SA", category: ["MARKSMAN", "ASSASSIN"], imageUrl: images + "KAISA.png" },
    { id: 55, name: "KALISTA", category: ["MARKSMAN"], imageUrl: images + "KALISTA.png" },
    { id: 56, name: "KARMA", category: ["MAGE", "SUPPORT"], imageUrl: images + "KARMA.png" },
    { id: 57, name: "KARTHUS", category: ["MAGE"], imageUrl: images + "KARTHUS.png" },
    { id: 58, name: "KASSADIN", category: ["ASSASSIN", "MAGE"], imageUrl: images + "KASSADIN.png" },
    { id: 59, name: "KATARINA", category: ["ASSASSIN", "MAGE"], imageUrl: images + "KATARINA.png" },
    { id: 60, name: "KAYLE", category: ["FIGHTER", "MARKSMAN"], imageUrl: images + "KAYLE.png" },
    { id: 61, name: "KAYN", category: ["ASSASSIN", "FIGHTER"], imageUrl: images + "KAYN.png" },
    { id: 62, name: "KENNEN", category: ["MAGE", "MARKSMAN"], imageUrl: images + "KENNEN.png" },
    { id: 63, name: "KHA'ZIX", category: ["ASSASSIN", "FIGHTER"], imageUrl: images + "KHAZIX.png" },
    { id: 64, name: "KINDRED", category: ["MARKSMAN"], imageUrl: images + "KINDRED.png" },
    { id: 65, name: "KLED", category: ["FIGHTER", "TANK"], imageUrl: images + "KLED.png" },
    { id: 66, name: "KOG'MAW", category: ["MARKSMAN", "MAGE"], imageUrl: images + "KOGMAW.png" },
    { id: 67, name: "LEBLANC", category: ["ASSASSIN", "MAGE"], imageUrl: images + "LEBLANC.png" },
    { id: 68, name: "LEE SIN", category: ["FIGHTER", "ASSASSIN"], imageUrl: images + "LEESIN.png" },
    { id: 69, name: "LEONA", category: ["TANK", "SUPPORT"], imageUrl: images + "LEONA.png" },
    { id: 70, name: "LILLIA", category: ["FIGHTER", "MAGE"], imageUrl: images + "LILLIA.png" },
    { id: 71, name: "LISSANDRA", category: ["MAGE"], imageUrl: images + "LISSANDRA.png" },
    { id: 72, name: "LUCIAN", category: ["MARKSMAN"], imageUrl: images + "LUCIAN.png" },
    { id: 73, name: "LULU", category: ["SUPPORT", "MAGE"], imageUrl: images + "LULU.png" },
    { id: 74, name: "LUX", category: ["MAGE", "SUPPORT"], imageUrl: images + "LUX.png" },
    { id: 75, name: "MALPHITE", category: ["TANK", "FIGHTER"], imageUrl: images + "MALPHITE.png" },
    { id: 76, name: "MALZAHAR", category: ["MAGE", "ASSASSIN"], imageUrl: images + "MALZAHAR.png" },
    { id: 77, name: "MAOKAI", category: ["TANK", "SUPPORT"], imageUrl: images + "MAOKAI.png" },
    { id: 78, name: "MASTER YI", category: ["ASSASSIN", "FIGHTER"], imageUrl: images + "MASTERYI.png" },
    { id: 79, name: "MISS FORTUNE", category: ["MARKSMAN"], imageUrl: images + "MISS_FORTUNE.png" },
    { id: 80, name: "MORDEKAISER", category: ["FIGHTER", "TANK"], imageUrl: images + "MORDEKAISER.png" },
    { id: 81, name: "MORGANA", category: ["MAGE", "SUPPORT"], imageUrl: images + "MORGANA.png" },
    { id: 82, name: "NAMI", category: ["SUPPORT", "MAGE"], imageUrl: images + "NAMI.png" },
    { id: 83, name: "NASUS", category: ["FIGHTER", "TANK"], imageUrl: images + "NASUS.png" },
    { id: 84, name: "NAUTILUS", category: ["TANK", "SUPPORT"], imageUrl: images + "NAUTILUS.png" },
    { id: 85, name: "NEEKO", category: ["MAGE", "SUPPORT"], imageUrl: images + "NEEKO.png" },
    { id: 86, name: "NIDALEE", category: ["ASSASSIN", "MAGE"], imageUrl: images + "NIDALEE.png" },
    { id: 87, name: "NOCTURNE", category: ["ASSASSIN", "FIGHTER"], imageUrl: images + "NOCTURNE.png" },
    { id: 88, name: "NUNU & WILLUMP", category: ["TANK", "FIGHTER"], imageUrl: images + "NUNU.png" },
    { id: 89, name: "OLAF", category: ["FIGHTER", "TANK"], imageUrl: images + "OLAF.png" },
    { id: 90, name: "ORIANNA", category: ["MAGE", "SUPPORT"], imageUrl: images + "ORIANNA.png" },
    { id: 91, name: "ORNN", category: ["TANK", "FIGHTER"], imageUrl: images + "ORNN.png" },
    { id: 92, name: "PANTHEON", category: ["FIGHTER", "ASSASSIN"], imageUrl: images + "PANTHEON.png" },
    { id: 93, name: "POPPY", category: ["TANK", "FIGHTER"], imageUrl: images + "POPPY.png" },
    { id: 94, name: "PYKE", category: ["ASSASSIN", "SUPPORT"], imageUrl: images + "PYKE.png" },
    { id: 95, name: "QIYANA", category: ["ASSASSIN", "FIGHTER"], imageUrl: images + "QIYANA.png" },
    { id: 96, name: "QUINN", category: ["MARKSMAN", "FIGHTER"], imageUrl: images + "QUINN.png" },
    { id: 97, name: "RAKAN", category: ["SUPPORT"], imageUrl: images + "RAKAN.png" },
    { id: 98, name: "RAMMUS", category: ["TANK", "FIGHTER"], imageUrl: images + "RAMMUS.png" },
    { id: 99, name: "REK'SAI", category: ["FIGHTER"], imageUrl: images + "REKSAI.png" },
    { id: 100, name: "RELL", category: ["TANK", "SUPPORT"], imageUrl: images + "RELL.png" },
    { id: 101, name: "RENEKTON", category: ["FIGHTER", "TANK"], imageUrl: images + "RENEKTON.png" },
    { id: 102, name: "RENATA GLASC", category: ["TANK", "FIGHTER"], imageUrl: images + "RENATA_GLASC.png" },
    { id: 103, name: "RENGAR", category: ["ASSASSIN", "FIGHTER"], imageUrl: images + "RENGAR.png" },
    { id: 104, name: "RIVEN", category: ["FIGHTER", "ASSASSIN"], imageUrl: images + "RIVEN.png" },
    { id: 105, name: "RUMBLE", category: ["FIGHTER", "MAGE"], imageUrl: images + "RUMBLE.png" },
    { id: 106, name: "RYZE", category: ["MAGE", "FIGHTER"], imageUrl: images + "RYZE.png" },
    { id: 107, name: "SAMIRA", category: ["MARKSMAN"], imageUrl: images + "SAMIRA.png" },
    { id: 108, name: "SEJUANI", category: ["TANK", "FIGHTER"], imageUrl: images + "SEJUANI.png" },
    { id: 109, name: "SENNA", category: ["MARKSMAN", "SUPPORT"], imageUrl: images + "SENNA.png" },
    { id: 110, name: "SERAPHINE", category: ["MAGE", "SUPPORT"], imageUrl: images + "SERAPHINE.png" },
    { id: 111, name: "SETT", category: ["FIGHTER", "TANK"], imageUrl: images + "SETT.png" },
    { id: 112, name: "SHACO", category: ["ASSASSIN"], imageUrl: images + "SHACO.png" },
    { id: 113, name: "SHEN", category: ["TANK", "SUPPORT"], imageUrl: images + "SHEN.png" },
    { id: 114, name: "SHYVANA", category: ["FIGHTER", "TANK"], imageUrl: images + "SHYVANA.png" },
    { id: 115, name: "SINGED", category: ["TANK", "FIGHTER"], imageUrl: images + "SINGED.png" },
    { id: 116, name: "SION", category: ["TANK", "FIGHTER"], imageUrl: images + "SION.png" },
    { id: 117, name: "SIVIR", category: ["MARKSMAN"], imageUrl: images + "SIVIR.png" },
    { id: 118, name: "SKARNER", category: ["FIGHTER", "TANK"], imageUrl: images + "SKARNER.png" },
    { id: 119, name: "SONA", category: ["SUPPORT", "MAGE"], imageUrl: images + "SONA.png" },
    { id: 120, name: "SORAKA", category: ["SUPPORT", "MAGE"], imageUrl: images + "SORAKA.png" },
    { id: 121, name: "SWAIN", category: ["MAGE", "FIGHTER"], imageUrl: images + "SWAIN.png" },
    { id: 122, name: "SYLAS", category: ["MAGE", "FIGHTER"], imageUrl: images + "SYLAS.png" },
    { id: 123, name: "SYNDRA", category: ["MAGE"], imageUrl: images + "SYNDRA.png" },
    { id: 124, name: "TAHM KENCH", category: ["TANK", "SUPPORT"], imageUrl: images + "TAHM_KENCH.png" },
    { id: 125, name: "TALIYAH", category: ["MAGE", "FIGHTER"], imageUrl: images + "TALIYAH.png" },
    { id: 126, name: "TALON", category: ["ASSASSIN"], imageUrl: images + "TALON.png" },
    { id: 127, name: "TARIC", category: ["TANK", "SUPPORT"], imageUrl: images + "TARIC.png" },
    { id: 128, name: "TEEMO", category: ["MARKSMAN", "ASSASSIN"], imageUrl: images + "TEEMO.png" },
    { id: 129, name: "THRESH", category: ["SUPPORT", "FIGHTER"], imageUrl: images + "THRESH.png" },
    { id: 130, name: "TRISTANA", category: ["MARKSMAN", "ASSASSIN"], imageUrl: images + "TRISTANA.png" },
    { id: 131, name: "TRUNDLE", category: ["FIGHTER", "TANK"], imageUrl: images + "TRUNDLE.png" },
    { id: 132, name: "TRYNDAMERE", category: ["FIGHTER", "ASSASSIN"], imageUrl: images + "TRYNDAMERE.png" },
    { id: 133, name: "TWISTED FATE", category: ["MAGE", "MARKSMAN"], imageUrl: images + "TWISTED_FATE.png" },
    { id: 134, name: "TWITCH", category: ["MARKSMAN", "ASSASSIN"], imageUrl: images + "TWITCH.png" },
    { id: 135, name: "UDYR", category: ["FIGHTER", "TANK"], imageUrl: images + "UDYR.png" },
    { id: 136, name: "URGOT", category: ["FIGHTER", "TANK"], imageUrl: images + "URGOT.png" },
    { id: 137, name: "VARUS", category: ["MARKSMAN", "MAGE"], imageUrl: images + "VARUS.png" },
    { id: 138, name: "VAYNE", category: ["MARKSMAN", "ASSASSIN"], imageUrl: images + "VAYNE.png" },
    { id: 139, name: "VEIGAR", category: ["MAGE", "ASSASSIN"], imageUrl: images + "VEIGAR.png" },
    { id: 140, name: "VEL'KOZ", category: ["MAGE"], imageUrl: images + "VELKOZ.png" },
    { id: 141, name: "VI", category: ["FIGHTER", "ASSASSIN"], imageUrl: images + "VI.png" },
    { id: 142, name: "VIEGO", category: ["ASSASSIN", "FIGHTER"], imageUrl: images + "VIEGO.png" },
    { id: 143, name: "VIKTOR", category: ["MAGE"], imageUrl: images + "VIKTOR.png" },
    { id: 144, name: "VLADIMIR", category: ["MAGE"], imageUrl: images + "VLADIMIR.png" },
    { id: 145, name: "VOLIBEAR", category: ["FIGHTER", "TANK"], imageUrl: images + "VOLIBEAR.png" },
    { id: 146, name: "WARWICK", category: ["FIGHTER", "TANK"], imageUrl: images + "WARWICK.png" },
    { id: 147, name: "WUKONG", category: ["FIGHTER", "ASSASSIN"], imageUrl: images + "WUKONG.png" },
    { id: 148, name: "XAYAH", category: ["MARKSMAN"], imageUrl: images + "XAYAH.png" },
    { id: 149, name: "XERATH", category: ["MAGE"], imageUrl: images + "XERATH.png" },
    { id: 150, name: "XIN ZHAO", category: ["FIGHTER", "ASSASSIN"], imageUrl: images + "XIN_ZHAO.png" },
    { id: 151, name: "YASUO", category: ["FIGHTER", "ASSASSIN"], imageUrl: images + "YASUO.png" },
    { id: 152, name: "YONE", category: ["ASSASSIN", "FIGHTER"], imageUrl: images + "YONE.png" },
    { id: 153, name: "YORICK", category: ["FIGHTER", "TANK"], imageUrl: images + "YORICK.png" },
    { id: 154, name: "YUUMI", category: ["SUPPORT", "MAGE"], imageUrl: images + "YUUMI.png" },
    { id: 155, name: "ZAC", category: ["TANK", "FIGHTER"], imageUrl: images + "ZAC.png" },
    { id: 156, name: "ZED", category: ["ASSASSIN"], imageUrl: images + "ZED.png" },
    { id: 157, name: "ZIGGS", category: ["MAGE"], imageUrl: images + "ZIGGS.png" },
    { id: 158, name: "ZILEAN", category: ["SUPPORT", "MAGE"], imageUrl: images + "ZILEAN.png" },
    { id: 159, name: "ZOE", category: ["MAGE"], imageUrl: images + "ZOE.png" },
    { id: 160, name: "ZYRA", category: ["MAGE", "SUPPORT"], imageUrl: images + "ZYRA.png" }
];