export interface Champion {
    name: string;
    category: string[];
    imageUrl: string;
}

const images = "/images/champions";
export const champions: Champion[] = [
    { name: "AATROX", category: ["FIGHTER"], imageUrl: images + "AATROX.png" },
    { name: "AHRI", category: ["MAGE", "ASSASSIN"], imageUrl: images + "AHRI.png" },
    { name: "AKALI", category: ["ASSASSIN"], imageUrl: images + "AKALI.png" },
    { name: "AKSHAN", category: ["MARKSMAN", "ASSASSIN"], imageUrl: images + "AKSHAN.png" },
    { name: "ALISTAR", category: ["TANK", "SUPPORT"], imageUrl: images + "ALISTAR.png" },
    { name: "AMUMU", category: ["TANK", "SUPPORT"], imageUrl: images + "AMUMU.png" },
    { name: "ANIVIA", category: ["MAGE"], imageUrl: images + "ANIVIA.png" },
    { name: "ANNIE", category: ["MAGE"], imageUrl: images + "ANNIE.png" },
    { name: "APHELIOS", category: ["MARKSMAN"], imageUrl: images + "APHELIOS.png" },
    { name: "ASHE", category: ["MARKSMAN", "SUPPORT"], imageUrl: images + "ASHE.png" },
    { name: "AURELION SOL", category: ["MAGE"], imageUrl: images + "AURELION_SOL.png" },
    { name: "AZIR", category: ["MAGE", "MARKSMAN"], imageUrl: images + "AZIR.png" },
    { name: "BARD", category: ["SUPPORT", "MAGE"], imageUrl: images + "BARD.png" },
    { name: "BEL´VETH", category: ["SUPPORT", "MAGE"], imageUrl: images + "BELVETH.png" },
    { name: "BLITZCRANK", category: ["TANK", "SUPPORT"], imageUrl: images + "BLITZCRANK.png" },
    { name: "BRAUM", category: ["SUPPORT", "TANK"], imageUrl: images + "BRAUM.png" },
    { name: "BRIAR", category: ["FIGHTER", "ASSASSIN"], imageUrl: images + "BRIAR.png" },
    { name: "CAITLYN", category: ["MARKSMAN"], imageUrl: images + "CAITLYN.png" },
    { name: "CAMILLE", category: ["FIGHTER"], imageUrl: images + "CAMILLE.png" },
    { name: "CASSIOPEIA", category: ["MAGE"], imageUrl: images + "CASSIOPEIA.png" },
    { name: "CHO'GATH", category: ["TANK", "MAGE"], imageUrl: images + "CHOGATH.png" },
    { name: "CORKI", category: ["MARKSMAN"], imageUrl: images + "CORKI.png" },
    { name: "DARIUS", category: ["FIGHTER", "TANK"], imageUrl: images + "DARIUS.png" },
    { name: "DIANA", category: ["FIGHTER", "MAGE"], imageUrl: images + "DIANA.png" },
    { name: "DR. MUNDO", category: ["FIGHTER", "TANK"], imageUrl: images + "DR_MUNDO.png" },
    { name: "DRAVEN", category: ["MARKSMAN"], imageUrl: images + "DRAVEN.png" },
    { name: "EKKO", category: ["ASSASSIN", "FIGHTER"], imageUrl: images + "EKKO.png" },
    { name: "ELISE", category: ["MAGE", "FIGHTER"], imageUrl: images + "ELISE.png" },
    { name: "EVELYNN", category: ["ASSASSIN", "MAGE"], imageUrl: images + "EVELYNN.png" },
    { name: "EZREAL", category: ["MARKSMAN", "MAGE"], imageUrl: images + "EZREAL.png" },
    { name: "FLCKS", category: ["MAGE", "SUPPORT"], imageUrl: images + "FLCKS.png" },
    { name: "FIORA", category: ["FIGHTER", "ASSASSIN"], imageUrl: images + "FIORA.png" },
    { name: "FIZZ", category: ["ASSASSIN", "FIGHTER"], imageUrl: images + "FIZZ.png" },
    { name: "GALIO", category: ["TANK", "MAGE"], imageUrl: images + "GALIO.png" },
    { name: "GANGPLANK", category: ["FIGHTER"], imageUrl: images + "GANGPLANK.png" },
    { name: "GAREN", category: ["FIGHTER", "TANK"], imageUrl: images + "GAREN.png" },
    { name: "GNAR", category: ["FIGHTER", "TANK"], imageUrl: images + "GNAR.png" },
    { name: "GRAGAS", category: ["FIGHTER", "MAGE"], imageUrl: images + "GRAGAS.png" },
    { name: "GRAVES", category: ["MARKSMAN"], imageUrl: images + "GRAVES.png" },
    { name: "GWEN", category: ["FIGHTER"], imageUrl: images + "GWEN.png" },
    { name: "HECARIM", category: ["FIGHTER", "TANK"], imageUrl: images + "HECARIM.png" },
    { name: "HEIMERDINGER", category: ["MAGE", "SUPPORT"], imageUrl: images + "HEIMERDINGER.png" },
    { name: "HWEI", category: ["FIGHTER", "TANK"], imageUrl: images + "HWEI.png" },
    { name: "ILLAOI", category: ["FIGHTER", "TANK"], imageUrl: images + "ILLAOI.png" },
    { name: "IRELIA", category: ["FIGHTER", "ASSASSIN"], imageUrl: images + "IRELIA.png" },
    { name: "IVERN", category: ["SUPPORT", "MAGE"], imageUrl: images + "IVERN.png" },
    { name: "JANNA", category: ["SUPPORT", "MAGE"], imageUrl: images + "JANNA.png" },
    { name: "JARVAN IV", category: ["TANK", "FIGHTER"], imageUrl: images + "JARVAN_IV.png" },
    { name: "JAX", category: ["FIGHTER", "ASSASSIN"], imageUrl: images + "JAX.png" },
    { name: "JAYCE", category: ["FIGHTER", "MARKSMAN"], imageUrl: images + "JAYCE.png" },
    { name: "JHIN", category: ["MARKSMAN", "MAGE"], imageUrl: images + "JHIN.png" },
    { name: "JINX", category: ["MARKSMAN"], imageUrl: images + "JINX.png" },
    { name: "K´SANTE", category: ["MARKSMAN", "ASSASSIN"], imageUrl: images + "KSANTE.png" },
    { name: "KAI'SA", category: ["MARKSMAN", "ASSASSIN"], imageUrl: images + "KAISA.png" },
    { name: "KALISTA", category: ["MARKSMAN"], imageUrl: images + "KALISTA.png" },
    { name: "KARMA", category: ["MAGE", "SUPPORT"], imageUrl: images + "KARMA.png" },
    { name: "KARTHUS", category: ["MAGE"], imageUrl: images + "KARTHUS.png" },
    { name: "KASSADIN", category: ["ASSASSIN", "MAGE"], imageUrl: images + "KASSADIN.png" },
    { name: "KATARINA", category: ["ASSASSIN", "MAGE"], imageUrl: images + "KATARINA.png" },
    { name: "KAYLE", category: ["FIGHTER", "MARKSMAN"], imageUrl: images + "KAYLE.png" },
    { name: "KAYN", category: ["ASSASSIN", "FIGHTER"], imageUrl: images + "KAYN.png" },
    { name: "KENNEN", category: ["MAGE", "MARKSMAN"], imageUrl: images + "KENNEN.png" },
    { name: "KHA'ZIX", category: ["ASSASSIN", "FIGHTER"], imageUrl: images + "KHAZIX.png" },
    { name: "KINDRED", category: ["MARKSMAN"], imageUrl: images + "KINDRED.png" },
    { name: "KLED", category: ["FIGHTER", "TANK"], imageUrl: images + "KLED.png" },
    { name: "KOG'MAW", category: ["MARKSMAN", "MAGE"], imageUrl: images + "KOGMAW.png" },
    { name: "LEBLANC", category: ["ASSASSIN", "MAGE"], imageUrl: images + "LEBLANC.png" },
    { name: "LEE SIN", category: ["FIGHTER", "ASSASSIN"], imageUrl: images + "LEESIN.png" },
    { name: "LEONA", category: ["TANK", "SUPPORT"], imageUrl: images + "LEONA.png" },
    { name: "LILLIA", category: ["FIGHTER", "MAGE"], imageUrl: images + "LILLIA.png" },
    { name: "LISSANDRA", category: ["MAGE"], imageUrl: images + "LISSANDRA.png" },
    { name: "LUCIAN", category: ["MARKSMAN"], imageUrl: images + "LUCIAN.png" },
    { name: "LULU", category: ["SUPPORT", "MAGE"], imageUrl: images + "LULU.png" },
    { name: "LUX", category: ["MAGE", "SUPPORT"], imageUrl: images + "LUX.png" },
    { name: "MALPHITE", category: ["TANK", "FIGHTER"], imageUrl: images + "MALPHITE.png" },
    { name: "MALZAHAR", category: ["MAGE", "ASSASSIN"], imageUrl: images + "MALZAHAR.png" },
    { name: "MAOKAI", category: ["TANK", "SUPPORT"], imageUrl: images + "MAOKAI.png" },
    { name: "MASTER YI", category: ["ASSASSIN", "FIGHTER"], imageUrl: images + "MASTERYI.png" },
    { name: "MISS FORTUNE", category: ["MARKSMAN"], imageUrl: images + "MISS_FORTUNE.png" },
    { name: "MORDEKAISER", category: ["FIGHTER", "TANK"], imageUrl: images + "MORDEKAISER.png" },
    { name: "MORGANA", category: ["MAGE", "SUPPORT"], imageUrl: images + "MORGANA.png" },
    { name: "NAMI", category: ["SUPPORT", "MAGE"], imageUrl: images + "NAMI.png" },
    { name: "NASUS", category: ["FIGHTER", "TANK"], imageUrl: images + "NASUS.png" },
    { name: "NAUTILUS", category: ["TANK", "SUPPORT"], imageUrl: images + "NAUTILUS.png" },
    { name: "NEEKO", category: ["MAGE", "SUPPORT"], imageUrl: images + "NEEKO.png" },
    { name: "NLng",category: ["ASSASSIN", "MAGE"], imageUrl: images + "NLng" },
    { name: "NOCTURNE", category: ["ASSASSIN", "FIGHTER"], imageUrl: images + "NOCTURNE.png" },
    { name: "NUNU & WILLUMP", category: ["TANK", "FIGHTER"], imageUrl: images + "NUNU.png" },
    { name: "OLAF", category: ["FIGHTER", "TANK"], imageUrl: images + "OLAF.png" },
    { name: "ORIANNA", category: ["MAGE", "SUPPORT"], imageUrl: images + "ORIANNA.png" },
    { name: "ORNN", category: ["TANK", "FIGHTER"], imageUrl: images + "ORNN.png" },
    { name: "PANTHEON", category: ["FIGHTER", "ASSASSIN"], imageUrl: images + "PANTHEON.png" },
    { name: "POPPY", category: ["TANK", "FIGHTER"], imageUrl: images + "POPPY.png" },
    { name: "PYKE", category: ["ASSASSIN", "SUPPORT"], imageUrl: images + "PYKE.png" },
    { name: "QIYANA", category: ["ASSASSIN", "FIGHTER"], imageUrl: images + "QIYANA.png" },
    { name: "QUINN", category: ["MARKSMAN", "FIGHTER"], imageUrl: images + "QUINN.png" },
    { name: "RAKAN", category: ["SUPPORT"], imageUrl: images + "RAKAN.png" },
    { name: "RAMMUS", category: ["TANK", "FIGHTER"], imageUrl: images + "RAMMUS.png" },
    { name: "REK'SAI", category: ["FIGHTER"], imageUrl: images + "REKSAI.png" },
    { name: "RELL", category: ["TANK", "SUPPORT"], imageUrl: images + "RELL.png" },
    { name: "RENEKTON", category: ["FIGHTER", "TANK"], imageUrl: images + "RENEKTON.png" },
    { name: "RENATA GLASC", category: ["TANK", "FIGHTER"], imageUrl: images + "RENATA_GLASC.png" },
    { name: "RENGAR", category: ["ASSASSIN", "FIGHTER"], imageUrl: images + "RENGAR.png" },
    { name: "RIVEN", category: ["FIGHTER", "ASSASSIN"], imageUrl: images + "RIVEN.png" },
    { name: "RUMBLE", category: ["FIGHTER", "MAGE"], imageUrl: images + "RUMBLE.png" },
    { name: "RYZE", category: ["MAGE", "FIGHTER"], imageUrl: images + "RYZE.png" },
    { name: "SAMIRA", category: ["MARKSMAN"], imageUrl: images + "SAMIRA.png" },
    { name: "SEJUANI", category: ["TANK", "FIGHTER"], imageUrl: images + "SEJUANI.png" },
    { name: "SENNA", category: ["MARKSMAN", "SUPPORT"], imageUrl: images + "SENNA.png" },
    { name: "SERAPHINE", category: ["MAGE", "SUPPORT"], imageUrl: images + "SERAPHINE.png" },
    { name: "SETT", category: ["FIGHTER", "TANK"], imageUrl: images + "SETT.png" },
    { name: "SHACO", category: ["ASSASSIN"], imageUrl: images + "SHACO.png" },
    { name: "SHEN", category: ["TANK", "SUPPORT"], imageUrl: images + "SHEN.png" },
    { name: "SHYVANA", category: ["FIGHTER", "TANK"], imageUrl: images + "SHYVANA.png" },
    { name: "SINGED", category: ["TANK", "FIGHTER"], imageUrl: images + "SINGED.png" },
    { name: "SION", category: ["TANK", "FIGHTER"], imageUrl: images + "SION.png" },
    { name: "SIVIR", category: ["MARKSMAN"], imageUrl: images + "SIVIR.png" },
    { name: "SKARNER", category: ["FIGHTER", "TANK"], imageUrl: images + "SKARNER.png" },
    { name: "SONA", category: ["SUPPORT", "MAGE"], imageUrl: images + "SONA.png" },
    { name: "SORAKA", category: ["SUPPORT", "MAGE"], imageUrl: images + "SORAKA.png" },
    { name: "SWAIN", category: ["MAGE", "FIGHTER"], imageUrl: images + "SWAIN.png" },
    { name: "SYLAS", category: ["MAGE", "FIGHTER"], imageUrl: images + "SYLAS.png" },
    { name: "SYNDRA", category: ["MAGE"], imageUrl: images + "SYNDRA.png" },
    { name: "TAHM KENCH", category: ["TANK", "SUPPORT"], imageUrl: images + "TAHM_KENCH.png" },
    { name: "TALIYAH", category: ["MAGE", "FIGHTER"], imageUrl: images + "TALIYAH.png" },
    { name: "TALON", category: ["ASSASSIN"], imageUrl: images + "TALON.png" },
    { name: "TARIC", category: ["TANK", "SUPPORT"], imageUrl: images + "TARIC.png" },
    { name: "TEEMO", category: ["MARKSMAN", "ASSASSIN"], imageUrl: images + "TEEMO.png" },
    { name: "THRESH", category: ["SUPPORT", "FIGHTER"], imageUrl: images + "THRESH.png" },
    { name: "TRISTANA", category: ["MARKSMAN", "ASSASSIN"], imageUrl: images + "TRISTANA.png" },
    { name: "TRUNDLE", category: ["FIGHTER", "TANK"], imageUrl: images + "TRUNDLE.png" },
    { name: "TRYNDAMERE", category: ["FIGHTER", "ASSASSIN"], imageUrl: images + "TRYNDAMERE.png" },
    { name: "TWISTED FATE", category: ["MAGE", "MARKSMAN"], imageUrl: images + "TWISTED_FATE.png" },
    { name: "TWITCH", category: ["MARKSMAN", "ASSASSIN"], imageUrl: images + "TWITCH.png" },
    { name: "UDYR", category: ["FIGHTER", "TANK"], imageUrl: images + "UDYR.png" },
    { name: "URGOT", category: ["FIGHTER", "TANK"], imageUrl: images + "URGOT.png" },
    { name: "VARUS", category: ["MARKSMAN", "MAGE"], imageUrl: images + "VARUS.png" },
    { name: "VAYNE", category: ["MARKSMAN", "ASSASSIN"], imageUrl: images + "VAYNE.png" },
    { name: "VEIGAR", category: ["MAGE", "ASSASSIN"], imageUrl: images + "VEIGAR.png" },
    { name: "VEL'KOZ", category: ["MAGE"], imageUrl: images + "VELKOZ.png" },
    { name: "VI", category: ["FIGHTER", "ASSASSIN"], imageUrl: images + "VI.png" },
    { name: "VIEGO", category: ["ASSASSIN", "FIGHTER"], imageUrl: images + "VIEGO.png" },
    { name: "VIKTOR", category: ["MAGE"], imageUrl: images + "VIKTOR.png" },
    { name: "VLADIMIR", category: ["MAGE"], imageUrl: images + "VLADIMIR.png" },
    { name: "VOLIBEAR", category: ["FIGHTER", "TANK"], imageUrl: images + "VOLIBEAR.png" },
    { name: "WARWICK", category: ["FIGHTER", "TANK"], imageUrl: images + "WARWICK.png" },
    { name: "WUKONG", category: ["FIGHTER", "ASSASSIN"], imageUrl: images + "WUKONG.png" },
    { name: "XAYAH", category: ["MARKSMAN"], imageUrl: images + "XAYAH.png" },
    { name: "XERATH", category: ["MAGE"], imageUrl: images + "XERATH.png" },
    { name: "XIN ZHAO", category: ["FIGHTER", "ASSASSIN"], imageUrl: images + "XIN_ZHAO.png" },
    { name: "YASUO", category: ["FIGHTER", "ASSASSIN"], imageUrl: images + "YASUO.png" },
    { name: "YONE", category: ["ASSASSIN", "FIGHTER"], imageUrl: images + "YONE.png" },
    { name: "YORICK", category: ["FIGHTER", "TANK"], imageUrl: images + "YORICK.png" },
    { name: "YUUMI", category: ["SUPPORT", "MAGE"], imageUrl: images + "YUUMI.png" },
    { name: "ZAC", category: ["TANK", "FIGHTER"], imageUrl: images + "ZAC.png" },
    { name: "ZED", category: ["ASSASSIN"], imageUrl: images + "ZED.png" },
    { name: "ZIGGS", category: ["MAGE"], imageUrl: images + "ZIGGS.png" },
    { name: "ZILEAN", category: ["SUPPORT", "MAGE"], imageUrl: images + "ZILEAN.png" },
    { name: "ZOE", category: ["MAGE"], imageUrl: images + "ZOE.png" },
    { name: "ZYRA", category: ["MAGE", "SUPPORT"], imageUrl: images + "ZYRA.png" }
];